version: "3.9"

services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    container_name: hantek-server
    ports:
      - "8000:8000"
    environment:
      - NO_DEVICE=1
    volumes:
      - ./server:/app
  ui:
    build:
      context: ui/
      dockerfile: Dockerfile.dev
    container_name: hantek-ui
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/src