version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hantek-station
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - NO_DEVICE=1
    volumes:
      - ./server:/app
      - ./ui:/ui